name: Docker-image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish changed images
      uses: dawidd6/action-docker-publish-changed@v2
      with:
        docker_username: ${{secrets.DOCKERHUB_USERNAME}}
        docker_password: ${{secrets.DOCKERHUB_PASSWORD}}
        github_token: ${{secrets.GITHUB_TOKEN}}
        platforms: linux/amd64,linux/arm64,linux/arm
        tag: dev
